### PR TITLE
Fix gnome-mpv issue #1

### PR DESCRIPTION
**Pull request by nado**

### CODE REVIEW

**Comment by rilian-la-te** [comment]
Will it builds with lower GTK?

**Comment by nado** [comment]
No it wont, you need the gtk+3 from the gnome overlay. Upstream will maybe support again lower versions, but not for the moment.

**Comment by nado** [comment]
But it doesnt build at all for now so…

**Comment by rilian-la-te** [comment]
If you want merge, please make gentoo unstable gtk dep.

**Comment by nado** [comment]
I’m sorry I don’t understand what you mean, since `KEYWORDS="~alpha ~amd64 ~ppc ~ppc64 ~x86 ~x86-fbsd"`, it is already marked unstable. Could you point me to some doc about what you mean ?
English is not my mothertongue, so there’s that too…

**Comment by rilian-la-te** [comment]
I mean using gtk3 less than 3.20, what version of gtk3 is largest in gentoo repo?

**Comment by nado** [comment]
3.18

**Comment by nado** [comment]
Fixed now and compiling with 3.18 since this commit https://github.com/gnome-mpv/gnome-mpv/commit/ceeeef1f1de9fe9ca8a669d88d50136d13ceb52b

**Pull request merged**
